//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A collection of power system resources (within a given substation) including conducting equipment, protection relays, measurements, and telemetry.  A bay typically represents a physical grouping related to modularization of equipment.
    public class Bay : EquipmentContainer {
        
        /// Indicates the presence/absence of energy measurements.
        private System.Boolean? cim_bayEnergyMeasFlag;
        
        private const bool isBayEnergyMeasFlagMandatory = false;
        
        private const string _bayEnergyMeasFlagPrefix = "cim";
        
        /// Indicates the presence/absence of active/reactive power measurements.
        private System.Boolean? cim_bayPowerMeasFlag;
        
        private const bool isBayPowerMeasFlagMandatory = false;
        
        private const string _bayPowerMeasFlagPrefix = "cim";
        
        public virtual bool BayEnergyMeasFlag {
            get {
                return this.cim_bayEnergyMeasFlag.GetValueOrDefault();
            }
            set {
                this.cim_bayEnergyMeasFlag = value;
            }
        }
        
        public virtual bool BayEnergyMeasFlagHasValue {
            get {
                return this.cim_bayEnergyMeasFlag != null;
            }
        }
        
        public static bool IsBayEnergyMeasFlagMandatory {
            get {
                return isBayEnergyMeasFlagMandatory;
            }
        }
        
        public static string BayEnergyMeasFlagPrefix {
            get {
                return _bayEnergyMeasFlagPrefix;
            }
        }
        
        public virtual bool BayPowerMeasFlag {
            get {
                return this.cim_bayPowerMeasFlag.GetValueOrDefault();
            }
            set {
                this.cim_bayPowerMeasFlag = value;
            }
        }
        
        public virtual bool BayPowerMeasFlagHasValue {
            get {
                return this.cim_bayPowerMeasFlag != null;
            }
        }
        
        public static bool IsBayPowerMeasFlagMandatory {
            get {
                return isBayPowerMeasFlagMandatory;
            }
        }
        
        public static string BayPowerMeasFlagPrefix {
            get {
                return _bayPowerMeasFlagPrefix;
            }
        }
    }
}
